target-version = "py310"
line-length = 110
exclude = [
  ".git,",
  "__pycache__",
  "build",
  "ndcube/version.py",
]

[lint]
select = [
  "ALL"
]

[lint.per-file-ignores]
# Part of configuration, not a package.
"setup.py" = ["INP001"]
"conftest.py" = ["INP001"]
"docs/conf.py" = [
  "E402"  # Module imports not at top of file
]
"docs/*.py" = [
  "INP001",  # Implicit-namespace-package. The examples are not a package.
]
"__init__.py" = ["E402", "F401", "F403"]
"test_*.py" = ["B011", "D", "E402", "PGH001", "S101"]

[lint.pydocstyle]
convention = "numpy"
