name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

variables:
  "System.PreferGit": true
  Agent.Source.Git.ShallowFetchDepth: 1
  CI_NAME: Azure Pipelines
  CI_BUILD_ID: $(Build.BuildId)
  CI_BUILD_URL: "https://dev.azure.com/sunpy/ndcube/_build/results?buildId=$(Build.BuildId)"
  GIT_BRANCH: $[ coalesce(variables['System.PullRequest.SourceBranch'], variables['Build.SourceBranchName'], 'not-found') ]
  GIT_COMMIT_SHA: $[ coalesce(variables['System.PullRequest.SourceCommitId'], variables['Build.SourceVersion'], 'not-found') ]

jobs:
- template: azure-templates.yml
  parameters:
    name: Linux_36_offline
    os: linux
    tox: py36-offline --

- template: azure-templates.yml
  parameters:
    name: pycodestyle
    os: linux
    tox: pycodestyle --

- template: azure-templates.yml
  parameters:
    name: macOS_37_offline
    os: macos
    tox: py37-offline --

- template: azure-templates.yml
  parameters:
    name: Windows_36_offline
    os: windows
    tox: py36-offline --

- template: azure-templates.yml
  parameters:
    name: Linux_36_Conda_offline
    os: linux
    tox: conda --
