name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)
variables:
  CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
  CIBW_MANYLINUX_I686_IMAGE: manylinux2014

resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: sunpy
    name: OpenAstronomy/azure-pipelines-templates
    ref: master

trigger:
  branches:
    include:
    - '*'
    exclude:
    - '*backport*'
  tags:
    include:
    - 'v*'
    exclude:
    - '*dev*'
    - '*pre*'
    - '*post*'

schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
      - main
    always: true

pr:
  autoCancel: true

stages:
  - stage: FirstPhaseTests
    displayName: Core Tests
    jobs:
    - template: check-skip.yml@OpenAstronomy
    - template: run-tox-env.yml@OpenAstronomy
      parameters:
        submodules: false
        coverage: codecov
        toxdeps: tox-pypi-filter
        envs:
          - linux: py39

  - stage: SecondPhaseTests
    displayName: Stage 2 Tests
    dependsOn: FirstPhaseTests
    condition: and(succeeded(), ne(dependencies.FirstPhaseTests.outputs['check_skip.search.found'], 'true'))
    jobs:
    - template: run-tox-env.yml@OpenAstronomy
      parameters:
        default_python: '3.9'
        submodules: false
        coverage: codecov
        toxdeps: tox-pypi-filter
        libraries:
          apt:
            - graphviz
        envs:
          - macos: py37
          - windows: py38
          - linux: build_docs
            posargs: " "
            pytest: false
          - linux: py38-conda
            libraries: {}
          - linux: py38-devdeps

  # On branches which aren't main, and not Pull Requests, build the wheels but only upload them on tags
  - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
    - stage: Release
      dependsOn: SecondPhaseTests
      jobs:
      - template: publish.yml@OpenAstronomy
        parameters:
          # Only Upload to PyPI on tags
          ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}:
            pypi_connection_name : 'PyPI'
          test_extras: 'dev'
          test_command: 'pytest -p no:warnings --doctest-rst -m "not mpl_image_compare" --pyargs ndcube'
          submodules: false
          targets:
            - wheels_universal
            - sdist
